### PR TITLE
Cm 14 1

### PR DESCRIPTION
**Pull request by maulik9898**

### CODE REVIEW

**Comment by Parth-Kambli** [comment]
Share it on https://review.lineageos.org/#/q/project:LineageOS/android_device_yu_tomato

**Comment by SAIRNR** [comment]
Not working YU

**Comment by invisiblek** [comment]
This is an automated response.
We only accept patches through our gerrit instance.
https://review.lineageos.org

**Comment by h2o64** [comment]
@maulik9898 AOSPARADOX copy-pasta I love the respect you gave

**Pull request closed without merging**
